# Generated by Django 3.1 on 2021-10-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_rememberme'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscleGroup',
            field=models.TextField(default='Legs'),
        ),
    ]
