name: Backend CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: 'test-db'
          POSTGRES_USER: 'test-db-user'
          POSTGRES_PASSWORD: 'test-db-password'
          DB_PORT: '5432'
          DB_HOST: 'postgres'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend/secfit
      - name: Make migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate --run-syncdb
        working-directory: ./backend/secfit
      - name: Run tests
        env:
          POSTGRES_DB: 'test-db'
          POSTGRES_USER: 'test-db-user'
          POSTGRES_PASSWORD: 'test-db-password'
          DB_PORT: '5432'
          DB_HOST: 'postgres'
        run: python manage.py test
        working-directory: ./backend/secfit
